# NumPy Library Basics

The Numpy library is the core library for the scientific computing in python.It provides a high performance 
multidimensional array objects,and tools for working with these arrays.

One of the most commonly used functions of NumPy are NumPy arrays: The essential differences between lists and NumPy arrays are-


*   Less Memory
*   Fast
*   Convenient


lists gives you basic operation, but NumPy adds FFTs, convolutions, fast searching, basic statistics, linear algebra, histograms, etc.
The most important difference for data science is the ability to do element-wise calculations with NumPy arrays.

**axis 0 always refers to row and axis 1 always refers to column**

# Creating Arrays

In [0]:
import numpy as np

a=np.array([1,2,3]) #1d array
b=np.array([(1,2,7),(4,5,6)]) #2d array

# **Memory Difference between list and Numpy Arrays**

In [3]:
import time
import sys
S= range(1000)
print(sys.getsizeof(5)*len(S))
 
D= np.arange(1000)
print(D.size*D.itemsize)

28000
8000


# Placeholders

np.linspace(0,2,9)-----Add evenly spaced values between interval to array of length

np.zeros((1,2))-----Create and array filled with zeros

np.ones((1,2))-----Creates an array filled with ones

np.random.random((5,5))-----Creates random array

np.empty((2,2))-----Creates an empty array

In [0]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [0]:
d=np.arange(10,25,5)


In [0]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
e=np.full((2,2),7)

In [0]:
f=np.eye(2)

In [0]:
np.random.random((2,2))

array([[0.67231927, 0.01269229],
       [0.06806771, 0.71122386]])

In [0]:
np.empty((3,2))

array([[4.66382113e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

# Array

# 1. Array Properties


array.shape-----Dimensions (Rows,Columns)

len(array)-----Length of Array

array.ndim-----Number of Array Dimensions

array.size-----Number of Array Elements

array.dtype-----Data Type

array.astype(type)-----Converts to Data Type

type(array)-----Type of Array

In [0]:
a=np.array([3,5])

In [0]:
a.shape

(2,)

In [0]:
len(a)

2

In [0]:
a.ndim

1

In [0]:
a.size

2

In [0]:
a.dtype

dtype('int64')

In [0]:
a.astype

<function ndarray.astype>

In [0]:
type(a)

numpy.ndarray

# Arithmetic Operation 

np.add(x,y)Addition of x + y

np.substract(x,y)Subtraction of x - y

np.divide(x,y)
x / yDivision

np.multiply(x,y)
x @ yMultiplication

np.sqrt(x)SquareRoot

np.sin(x)Element-wise sine

np.cos(x)Element-wise cosine

np.log(x)Element-wise natural log

np.dot(x,y)Dot product

Remember: NumPy array operations work element-wise.

In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(np.add(a,b)) #Addition

[5 5]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(np.subtract(a,b)) #subtraction

[ 1 -1]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(np.divide(a,b)) #divide

[1.5        0.66666667]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(np.multiply(a,b)) #multiply

[6 6]


In [0]:
a=np.array([3,2])
print(np.sqrt(a)) #square

[1.73205081 1.41421356]


In [0]:
a=np.array([3,2])
print(np.sin(a)) #sin function

[0.14112001 0.90929743]


In [0]:
a=np.array([3,2])
print(np.cos(a)) #cos function

[-0.9899925  -0.41614684]


In [0]:
a=np.array([3,2])
print(np.log(a)) #log function

[1.09861229 0.69314718]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(np.dot(a,b)) # dot operation

12


# Comparison

In [0]:

== ----Equal

!= ----Not equal

< -----Smaller than

> -----Greater than

<= -----Smaller than or equal

>= -----Greater than or equal

np.array_equal(x,y) ------Array-wise comparison

In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(a==b) #Equal

[False False]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(a!=b) #Not equal


[ True  True]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(a<b) #Smaller than

[False  True]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(a>b) #Greater than

[ True False]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(a<=b) #Smaller than or equal

[False  True]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(a>=b) #Greater than or equal

[ True False]


In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(np.array_equal(a,b)) #Array-wise comparison

False


# Copying/Sorting


np.copy(array) -----Creates copy of array

other = array.copy() -----Creates deep copy of array

array.sort() -----Sorts an array

array.sort(axis=0) ----Sorts axis of array

In [0]:
a=np.array([3,2])
print(np.copy(a)) # Creates copy of array

[3 2]


In [0]:
a=np.array([3,2])
other=a.copy()
print(other) #Creates deep copy of array

[3 2]


In [0]:
a=np.array([3,2])
print(a.sort()) #Sorts an array

None


In [0]:
a=np.array([3,2])
print(a.sort(axis=0)) #Sorts axis of array

None


# Array Manipulation 


np.append(a,b)------Append items to array

np.insert(array, 1, 2, axis)-----Insert items into array at axis 0 or 1

array.resize((2,4))------Resize array to shape(2,4)

np.delete(array,1,axis)------Deletes items from array

In [0]:
a=np.array([3,2])
b=np.array([2,3])
print(np.append(a,b)) #Append items to array

[3 2 2 3]


In [0]:
a=np.array([3,2])
print(a.resize((2,4))) #Resize array to shape(2,4)

None


# Combining Arrays


np.concatenate((a,b),axis=0)------Concatenates 2 arrays, adds to end

np.vstack((a,b))-------Stack array row-wise

np.hstack((a,b))-------Stack array column wise

In [0]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])
print(np.concatenate((a,b),axis=0)) # Concatenates 2 arrays, adds to end

[1 3 5 2 4 6]


In [0]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])
print(np.vstack((a,b))) # Stack array row-wise

[[1 3 5]
 [2 4 6]]


In [0]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])
print(np.hstack((a,b))) #Stack array column wise

[1 3 5 2 4 6]


# Splitting Arrays

numpy.split()

np.array_split(array,3) -----Split an array in sub-arrays of (nearly) identical size

numpy.hsplit(array, 3) ----Split the array horizontally at 3rd index

In [0]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.array_split(a, 3)) #Split an array in sub-arrays of (nearly) identical size

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [0]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.hsplit(a,1)) #Split the array horizontally at 3rd index

[array([1, 2, 3, 4, 5, 6, 7, 8])]


# Slicing and Subsetting


array[i]-----1d array at index i

array[i,j]-----2d array at index[i][j]

array[i<4]-----Boolean Indexing

array[0:3]-----Select items of index 0, 1 and 2

array[0:2,1]-----Select items of rows 0 and 1 at column 1

array[:1]------Select items of row 0 (equals array[0:1, :])

array[1:2, :]------Select items of row 1

array[ : :-1]-----Reverses arraysee above

In [0]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b[0:1, 2])

[3]


In [0]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b[:len(b), 2])

[3 6]


In [0]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b[0, :])

[1 2 3]


In [0]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b[0, 2:])

[3]


In [0]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b[:, 0])

[1 4]


In [0]:
c = np.array([(1, 2, 3), (4, 5, 6)])
d = c[1:2, 0:2]
print(d)

[[4 5]]


# Basic Statistics


np.mean(array)-----Mean

np.median(array)----Median

array.corrcoef()-----Correlation Coefficient

array.std(array)-----Standard Deviation

In [0]:
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])
print(np.mean(a)) # Mean

6.25


In [0]:
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])
print(np.median(a)) #Median

6.5


In [0]:
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])
print(np.std(a)) #Standard Deviation

4.293891009329417


# Aggregrate Function

In [0]:
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])
a.sum() # Addition

50

In [0]:
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])
a.min() # minimum value

1

In [0]:
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])
a.max() # maximun value

12

In [0]:
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])
a.cumsum() # cumulative sum of the elements

array([ 1,  2,  4,  9, 17, 27, 38, 50])